---
name: CI/CD

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Working branch"
        type: string
        required: false
        default: ""
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  auto-lock:
    runs-on: ubuntu-latest
    name: Pin Docker Images
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: crazyrokr/gha-workflows/ha-addon-auto-locker@bf06d82937ae7f1dce4cc4d8075be49dfa97da53 # master
        with:
          branch: ${{ github.event.inputs.branch }}
          lookup_sources: Dockerfile
  run-builder:
    needs: auto-lock
    uses: crazyrokr/gha-workflows/.github/workflows/ha-addon-cicd.yaml@bf06d82937ae7f1dce4cc4d8075be49dfa97da53 # master
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write
